//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.1
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EnviarSNGPC.ServiceReference1 {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="ServiceReference1.sngpcSoap")]
    public interface sngpcSoap {
        
        // CODEGEN: Generating message contract since element name Email from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ValidarUsuario", ReplyAction="*")]
        EnviarSNGPC.ServiceReference1.ValidarUsuarioResponse ValidarUsuario(EnviarSNGPC.ServiceReference1.ValidarUsuarioRequest request);
        
        // CODEGEN: Generating message contract since element name Email from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/EnviaArquivoSNGPC", ReplyAction="*")]
        EnviarSNGPC.ServiceReference1.EnviaArquivoSNGPCResponse EnviaArquivoSNGPC(EnviarSNGPC.ServiceReference1.EnviaArquivoSNGPCRequest request);
        
        // CODEGEN: Generating message contract since element name Email from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ConsultaDadosArquivoSNGPC", ReplyAction="*")]
        EnviarSNGPC.ServiceReference1.ConsultaDadosArquivoSNGPCResponse ConsultaDadosArquivoSNGPC(EnviarSNGPC.ServiceReference1.ConsultaDadosArquivoSNGPCRequest request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class ValidarUsuarioRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="ValidarUsuario", Namespace="http://tempuri.org/", Order=0)]
        public EnviarSNGPC.ServiceReference1.ValidarUsuarioRequestBody Body;
        
        public ValidarUsuarioRequest() {
        }
        
        public ValidarUsuarioRequest(EnviarSNGPC.ServiceReference1.ValidarUsuarioRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class ValidarUsuarioRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string Email;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string Senha;
        
        public ValidarUsuarioRequestBody() {
        }
        
        public ValidarUsuarioRequestBody(string Email, string Senha) {
            this.Email = Email;
            this.Senha = Senha;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class ValidarUsuarioResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="ValidarUsuarioResponse", Namespace="http://tempuri.org/", Order=0)]
        public EnviarSNGPC.ServiceReference1.ValidarUsuarioResponseBody Body;
        
        public ValidarUsuarioResponse() {
        }
        
        public ValidarUsuarioResponse(EnviarSNGPC.ServiceReference1.ValidarUsuarioResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class ValidarUsuarioResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string ValidarUsuarioResult;
        
        public ValidarUsuarioResponseBody() {
        }
        
        public ValidarUsuarioResponseBody(string ValidarUsuarioResult) {
            this.ValidarUsuarioResult = ValidarUsuarioResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class EnviaArquivoSNGPCRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="EnviaArquivoSNGPC", Namespace="http://tempuri.org/", Order=0)]
        public EnviarSNGPC.ServiceReference1.EnviaArquivoSNGPCRequestBody Body;
        
        public EnviaArquivoSNGPCRequest() {
        }
        
        public EnviaArquivoSNGPCRequest(EnviarSNGPC.ServiceReference1.EnviaArquivoSNGPCRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class EnviaArquivoSNGPCRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string Email;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string Senha;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public byte[] Arq;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=3)]
        public string HashIdentificacao;
        
        public EnviaArquivoSNGPCRequestBody() {
        }
        
        public EnviaArquivoSNGPCRequestBody(string Email, string Senha, byte[] Arq, string HashIdentificacao) {
            this.Email = Email;
            this.Senha = Senha;
            this.Arq = Arq;
            this.HashIdentificacao = HashIdentificacao;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class EnviaArquivoSNGPCResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="EnviaArquivoSNGPCResponse", Namespace="http://tempuri.org/", Order=0)]
        public EnviarSNGPC.ServiceReference1.EnviaArquivoSNGPCResponseBody Body;
        
        public EnviaArquivoSNGPCResponse() {
        }
        
        public EnviaArquivoSNGPCResponse(EnviarSNGPC.ServiceReference1.EnviaArquivoSNGPCResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class EnviaArquivoSNGPCResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string EnviaArquivoSNGPCResult;
        
        public EnviaArquivoSNGPCResponseBody() {
        }
        
        public EnviaArquivoSNGPCResponseBody(string EnviaArquivoSNGPCResult) {
            this.EnviaArquivoSNGPCResult = EnviaArquivoSNGPCResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class ConsultaDadosArquivoSNGPCRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="ConsultaDadosArquivoSNGPC", Namespace="http://tempuri.org/", Order=0)]
        public EnviarSNGPC.ServiceReference1.ConsultaDadosArquivoSNGPCRequestBody Body;
        
        public ConsultaDadosArquivoSNGPCRequest() {
        }
        
        public ConsultaDadosArquivoSNGPCRequest(EnviarSNGPC.ServiceReference1.ConsultaDadosArquivoSNGPCRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class ConsultaDadosArquivoSNGPCRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string Email;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string Senha;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public string CNPJ;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=3)]
        public string Hash;
        
        public ConsultaDadosArquivoSNGPCRequestBody() {
        }
        
        public ConsultaDadosArquivoSNGPCRequestBody(string Email, string Senha, string CNPJ, string Hash) {
            this.Email = Email;
            this.Senha = Senha;
            this.CNPJ = CNPJ;
            this.Hash = Hash;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class ConsultaDadosArquivoSNGPCResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="ConsultaDadosArquivoSNGPCResponse", Namespace="http://tempuri.org/", Order=0)]
        public EnviarSNGPC.ServiceReference1.ConsultaDadosArquivoSNGPCResponseBody Body;
        
        public ConsultaDadosArquivoSNGPCResponse() {
        }
        
        public ConsultaDadosArquivoSNGPCResponse(EnviarSNGPC.ServiceReference1.ConsultaDadosArquivoSNGPCResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class ConsultaDadosArquivoSNGPCResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string ConsultaDadosArquivoSNGPCResult;
        
        public ConsultaDadosArquivoSNGPCResponseBody() {
        }
        
        public ConsultaDadosArquivoSNGPCResponseBody(string ConsultaDadosArquivoSNGPCResult) {
            this.ConsultaDadosArquivoSNGPCResult = ConsultaDadosArquivoSNGPCResult;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface sngpcSoapChannel : EnviarSNGPC.ServiceReference1.sngpcSoap, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class sngpcSoapClient : System.ServiceModel.ClientBase<EnviarSNGPC.ServiceReference1.sngpcSoap>, EnviarSNGPC.ServiceReference1.sngpcSoap {
        
        public sngpcSoapClient() {
        }
        
        public sngpcSoapClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public sngpcSoapClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public sngpcSoapClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public sngpcSoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        EnviarSNGPC.ServiceReference1.ValidarUsuarioResponse EnviarSNGPC.ServiceReference1.sngpcSoap.ValidarUsuario(EnviarSNGPC.ServiceReference1.ValidarUsuarioRequest request) {
            return base.Channel.ValidarUsuario(request);
        }
        
        public string ValidarUsuario(string Email, string Senha) {
            EnviarSNGPC.ServiceReference1.ValidarUsuarioRequest inValue = new EnviarSNGPC.ServiceReference1.ValidarUsuarioRequest();
            inValue.Body = new EnviarSNGPC.ServiceReference1.ValidarUsuarioRequestBody();
            inValue.Body.Email = Email;
            inValue.Body.Senha = Senha;
            EnviarSNGPC.ServiceReference1.ValidarUsuarioResponse retVal = ((EnviarSNGPC.ServiceReference1.sngpcSoap)(this)).ValidarUsuario(inValue);
            return retVal.Body.ValidarUsuarioResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        EnviarSNGPC.ServiceReference1.EnviaArquivoSNGPCResponse EnviarSNGPC.ServiceReference1.sngpcSoap.EnviaArquivoSNGPC(EnviarSNGPC.ServiceReference1.EnviaArquivoSNGPCRequest request) {
            return base.Channel.EnviaArquivoSNGPC(request);
        }
        
        public string EnviaArquivoSNGPC(string Email, string Senha, byte[] Arq, string HashIdentificacao) {
            EnviarSNGPC.ServiceReference1.EnviaArquivoSNGPCRequest inValue = new EnviarSNGPC.ServiceReference1.EnviaArquivoSNGPCRequest();
            inValue.Body = new EnviarSNGPC.ServiceReference1.EnviaArquivoSNGPCRequestBody();
            inValue.Body.Email = Email;
            inValue.Body.Senha = Senha;
            inValue.Body.Arq = Arq;
            inValue.Body.HashIdentificacao = HashIdentificacao;
            EnviarSNGPC.ServiceReference1.EnviaArquivoSNGPCResponse retVal = ((EnviarSNGPC.ServiceReference1.sngpcSoap)(this)).EnviaArquivoSNGPC(inValue);
            return retVal.Body.EnviaArquivoSNGPCResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        EnviarSNGPC.ServiceReference1.ConsultaDadosArquivoSNGPCResponse EnviarSNGPC.ServiceReference1.sngpcSoap.ConsultaDadosArquivoSNGPC(EnviarSNGPC.ServiceReference1.ConsultaDadosArquivoSNGPCRequest request) {
            return base.Channel.ConsultaDadosArquivoSNGPC(request);
        }
        
        public string ConsultaDadosArquivoSNGPC(string Email, string Senha, string CNPJ, string Hash) {
            EnviarSNGPC.ServiceReference1.ConsultaDadosArquivoSNGPCRequest inValue = new EnviarSNGPC.ServiceReference1.ConsultaDadosArquivoSNGPCRequest();
            inValue.Body = new EnviarSNGPC.ServiceReference1.ConsultaDadosArquivoSNGPCRequestBody();
            inValue.Body.Email = Email;
            inValue.Body.Senha = Senha;
            inValue.Body.CNPJ = CNPJ;
            inValue.Body.Hash = Hash;
            EnviarSNGPC.ServiceReference1.ConsultaDadosArquivoSNGPCResponse retVal = ((EnviarSNGPC.ServiceReference1.sngpcSoap)(this)).ConsultaDadosArquivoSNGPC(inValue);
            return retVal.Body.ConsultaDadosArquivoSNGPCResult;
        }
    }
}
